name: fgcart
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  alice: ^0.2.4
  cached_network_image: ^3.1.0
  cookie_jar: ^3.0.1
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  flutter:
    sdk: flutter
  flutter_palette: ^1.1.0+1
  flutter_widget_from_html_core: ^0.6.2
  freezed_annotation: ^0.14.2
  provider: ^5.0.0
  url_launcher: ^6.0.9

dev_dependencies: 
  build_runner: ^2.1.1
  freezed: ^0.14.2
  json_serializable: ^4.1.4
  lint: ^1.5.3

flutter:
  uses-material-design: true
